"""Core types for the execution engine: order state machine and executor protocol.

The order lifecycle is modelled as an explicit state machine with a fixed set
of valid transitions.  Any attempt to move to a non-adjacent state is caught
at the point of transition and logged at CRITICAL severity.

P0-3 Invariant
--------------
The three-state crash-safe flow is:

    PENDING_SUBMIT  ->  SUBMITTED  ->  FILLED | CANCELLED | EXPIRED

An order that is persisted in PENDING_SUBMIT but whose process then crashes can
be recovered by :class:`~execution.recovery.RecoveryWorker` on the next startup.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Protocol

# ---------------------------------------------------------------------------
# Order status enumeration
# ---------------------------------------------------------------------------


class OrderStatus(StrEnum):
    """All possible states an order can occupy during its lifecycle.

    Attributes:
        PENDING_SUBMIT: DB row written, exchange submit not yet attempted.
            This is the crash-safe checkpoint (P0-3).
        SUBMITTED: Order acknowledged by the exchange; awaiting a fill.
        PARTIAL: The exchange has partially filled the order.
        FILLED: Order fully filled — terminal state.
        CANCELLED: Cancelled by us or by the exchange — terminal state.
        EXPIRED: Exchange expired the order (e.g. GTC expired) — terminal.
        REJECTED: Rejected by the exchange or by our pre-flight checks — terminal.
    """

    PENDING_SUBMIT = "pending_submit"
    SUBMITTED = "submitted"
    PARTIAL = "partial"
    FILLED = "filled"
    CANCELLED = "cancelled"
    EXPIRED = "expired"
    REJECTED = "rejected"


# ---------------------------------------------------------------------------
# Valid state-transition graph
# ---------------------------------------------------------------------------

#: Maps each status to the set of states it may legally transition into.
VALID_TRANSITIONS: dict[OrderStatus, set[OrderStatus]] = {
    OrderStatus.PENDING_SUBMIT: {
        OrderStatus.SUBMITTED,
        OrderStatus.CANCELLED,
        OrderStatus.REJECTED,
    },
    OrderStatus.SUBMITTED: {
        OrderStatus.PARTIAL,
        OrderStatus.FILLED,
        OrderStatus.CANCELLED,
        OrderStatus.EXPIRED,
    },
    OrderStatus.PARTIAL: {
        OrderStatus.FILLED,
        OrderStatus.CANCELLED,
    },
    # Terminal states — no further transitions allowed.
    OrderStatus.FILLED: set(),
    OrderStatus.CANCELLED: set(),
    OrderStatus.EXPIRED: set(),
    OrderStatus.REJECTED: set(),
}

#: Convenience set of all terminal order states.
TERMINAL_STATES: frozenset[OrderStatus] = frozenset(
    status for status, targets in VALID_TRANSITIONS.items() if not targets
)


def validate_transition(current: OrderStatus, target: OrderStatus) -> bool:
    """Return ``True`` when transitioning from *current* to *target* is legal.

    Args:
        current: The order's present status.
        target: The desired next status.

    Returns:
        ``True`` if the transition is in :data:`VALID_TRANSITIONS`, ``False``
        otherwise (including when *current* is already a terminal state).
    """
    return target in VALID_TRANSITIONS.get(current, set())


# ---------------------------------------------------------------------------
# Order data structures
# ---------------------------------------------------------------------------


@dataclass
class OrderRecord:
    """In-memory representation of a single order's complete lifecycle.

    Attributes:
        client_order_id: Idempotency key generated by the engine.
        exchange_order_id: The exchange-assigned order identifier, or ``None``
            until the order is successfully submitted.
        pair: CCXT-formatted trading pair, e.g. ``"BTC/USDT"``.
        side: ``"buy"`` or ``"sell"``.
        requested_quantity: Quantity originally requested.
        filled_quantity: Quantity matched by the exchange so far.
        filled_price: Volume-weighted average fill price.
        status: Current :class:`OrderStatus`.
        fees: Cumulative fees paid for this order (quote-asset units).
        signal_id: Identifier of the originating :class:`~risk.base.ApprovedOrder`.
        created_at: Wall-clock time when the record was first created.
        updated_at: Wall-clock time of the most recent status change.
        transitions: Ordered audit trail of ``(status, timestamp)`` pairs.
    """

    client_order_id: str
    exchange_order_id: str | None = None
    pair: str = ""
    side: str = ""
    requested_quantity: float = 0.0
    filled_quantity: float = 0.0
    filled_price: float = 0.0
    status: OrderStatus = OrderStatus.PENDING_SUBMIT
    fees: float = 0.0
    signal_id: str = ""
    created_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    updated_at: datetime = field(default_factory=lambda: datetime.now(UTC))
    transitions: list[tuple[OrderStatus, datetime]] = field(default_factory=list)


@dataclass
class OrderResult:
    """Summarised outcome returned by an :class:`Executor` after order processing.

    Attributes:
        client_order_id: Idempotency key that links this result back to the
            original request.
        exchange_order_id: Exchange-assigned identifier, or ``None`` if the
            order was never submitted.
        status: Final (or current) :class:`OrderStatus`.
        filled_price: Average price at which the order was filled.
        filled_quantity: Total quantity matched.
        fees: Total fees charged (quote-asset units).
    """

    client_order_id: str
    exchange_order_id: str | None
    status: OrderStatus
    filled_price: float
    filled_quantity: float
    fees: float


# ---------------------------------------------------------------------------
# Executor protocol
# ---------------------------------------------------------------------------


class Executor(Protocol):
    """Structural protocol that every executor implementation must satisfy.

    Both :class:`~execution.paper_executor.PaperExecutor` and any live
    executor (e.g. a CCXT-backed implementation) conform to this interface.
    """

    async def place_order(
        self,
        pair: str,
        side: str,
        quantity: float,
        client_order_id: str,
    ) -> OrderResult:
        """Submit a new order and return an :class:`OrderResult`.

        Args:
            pair: CCXT-formatted trading pair.
            side: ``"buy"`` or ``"sell"``.
            quantity: Asset quantity to trade.
            client_order_id: Caller-provided idempotency key.

        Returns:
            An :class:`OrderResult` reflecting the order's immediate state.
        """
        ...

    async def cancel_order(self, client_order_id: str) -> bool:
        """Request cancellation of a previously placed order.

        Args:
            client_order_id: The idempotency key of the order to cancel.

        Returns:
            ``True`` if the cancellation succeeded, ``False`` otherwise.
        """
        ...

    async def get_order_status(self, client_order_id: str) -> OrderResult:
        """Fetch the current status of an order from the executor.

        Args:
            client_order_id: The idempotency key of the order to query.

        Returns:
            An :class:`OrderResult` with the latest known state.
        """
        ...
